import type { Metadata } from 'next';
import { Poppins, Open_Sans } from 'next/font/google';
import './globals.css';
import SkipToMain from '@/components/layout/SkipToMain';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const sans = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  style: ['normal', 'italic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`overflow-auto bg-stone-800 ${sans.variable} ${openSans.variable}`}
    >
      <body className={'overscroll-none bg-stone-800'}>
        <SkipToMain />
        <Header />
        {/* <div className='h-head'></div> */}
        <main
          id='mainContent'
          className={`bg-stone-950 min-h-fullscr font-sans`}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
