import type { Metadata } from 'next';
import { Inter, Pathway_Extreme } from 'next/font/google';
import './globals.css';
import SkipToMain from '@/components/layout/SkipToMain';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const sans = Pathway_Extreme({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pathex',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`overflow-auto bg-stone-800 ${sans.variable}`}>
      <body className={'overscroll-none bg-stone-800'}>
        <SkipToMain />
        <Header />
        <div className='h-head'></div>
        <main
          id='mainContent'
          className={`bg-stone-950 min-h-fullscr font-sans`}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
